/*:
 Second Exercise: **Comments**
 
 Removing code should be one of your activities as a developer. Always delete unused code also code that is generated by IDE. In code review when you see empty method, unused variable, outdated comments, imports hanging around your code, don’t just leave it, it should be removed.
 
 - Note: Mario has pushed this fantastic code in the common repository. Maybe he wrote to much comments. A good code doesn't need comments, so remove the comments.
*/

//#-editable-code
func getLabelDuplicated(label: String) -> String{
    //I'm returning "\(label)\(label)" duplicated
    return "\(label)\(label)"
}
//#-end-editable-code

//#-hidden-code
import PlaygroundSupport
import Foundation

public func findUserCodeInputs(from input: String) -> [String] {
    var inputs: [String] = []
    let scanner = Scanner(string: input)
    while scanner.scanUpTo("//#-editable-code", into: nil) {
        var userInput: NSString? = ""
        scanner.scanUpTo("\n", into: nil)
        scanner.scanUpTo("//#-end-editable-code", into: &userInput)
        
        if userInput != nil {
            inputs.append(String(userInput!))
        }
    }
    return inputs
}

public func makeAssessment(of input: String) {
    let codeInputs = findUserCodeInputs(from: input)
    if codeInputs[0].contains("//") || codeInputs[0].contains("returning"){
        PlaygroundPage.current.assessmentStatus = .fail(hints: ["Try again 🧐"], solution: "Remove the comments")
        return
    }
    PlaygroundPage.current.assessmentStatus = .pass(message: "Great job! Now continue with the next exercise")
}

makeAssessment(of: PlaygroundPage.current.text)
//#-end-hidden-code
